# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('InnerIp', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5185\u7f51IP\u5730\u5740')),
                ('OuterIp', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5916\u7f51IP\u5730\u5740')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='\u5382\u5546')),
                ('productname', models.CharField(max_length=30, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('sn', models.CharField(max_length=80, unique=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('cpu_model', models.CharField(max_length=50, verbose_name='CPU\u578b\u53f7')),
                ('cpu_nums', models.SmallIntegerField(verbose_name='CPU\u7ebf\u7a0b\u6570')),
                ('cpu_cores', models.PositiveSmallIntegerField(verbose_name='CPU\u7269\u7406\u6838\u6570')),
                ('mem', models.CharField(max_length=100, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(max_length=300, verbose_name='\u786c\u76d8\u5927\u5c0f')),
                ('os', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u8d44\u4ea7\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u8d44\u4ea7\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('InnerIp', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5185\u7f51IP\u5730\u5740')),
                ('OuterIp', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5916\u7f51IP\u5730\u5740')),
                ('hostname', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('application', models.CharField(max_length=20, verbose_name='\u5e94\u7528')),
                ('group', models.ManyToManyField(to='web.Group', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u5217\u8868',
                'verbose_name_plural': '\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=40, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('remark', models.CharField(max_length=40, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u5217\u8868',
                'verbose_name_plural': '\u673a\u623f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('task', models.CharField(max_length=64)),
                ('task_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('target_host', models.ManyToManyField(to='web.HostList')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u6d41\u7a0b',
                'verbose_name_plural': '\u4efb\u52a1\u6d41\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.FileField(upload_to='./uploads/')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20',
                'verbose_name_plural': '\u6587\u4ef6\u4e0a\u4f20',
            },
        ),
        migrations.AddField(
            model_name='hostlist',
            name='idc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Idc'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostList'),
        ),
    ]
