# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usergroup_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='token',
            field=models.CharField(default='cmdb', max_length=20, verbose_name='\u8d44\u4ea7\u4ee4\u724c'),
        ),
    ]
