# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_assets_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='idc',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
    ]
